version: "3.8"

services:
  test:
    build:
      context: .
      args:
        HDF5_VERSION: 1.12.2
        NETCDF_VERSION: 4.8.1
        R_LIBRARIES: "dplyr ncdf4 tidync"
        R_VERSION: 4.3.0
    command: "opendap_ncml_test.r"
    environment:
      CURLOPT_VERBOSE: 1
    volumes:
      - ./:/app/
